//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> end { get; set; }
        public string url { get; set; }
        public string className { get; set; }
        public Nullable<bool> editable { get; set; }
    }
}
