//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modulo()
        {
            this.ModuloEstudiantes = new HashSet<ModuloEstudiante>();
        }
    
        public string CodigoModulo { get; set; }
        public string NombreModulo { get; set; }
        public string Duracion { get; set; }
        public Nullable<int> Creditos { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdSede { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuloEstudiante> ModuloEstudiantes { get; set; }
        public virtual ModuloProfesor ModuloProfesor { get; set; }
    }
}
