//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesor()
        {
            this.ModuloProfesors = new HashSet<ModuloProfesor>();
        }
    
        public string Nombre { get; set; }
        public int Cedula { get; set; }
        public string FechaNacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Genero { get; set; }
        public Nullable<int> TelefonoMovil { get; set; }
        public Nullable<int> TelefonoDomicilio { get; set; }
        public string CorreoElectronico { get; set; }
        public string Provincia { get; set; }
        public string Canton { get; set; }
        public string Distrito { get; set; }
        public string DomicilioExacto { get; set; }
        public int NumeroCuenta { get; set; }
        public string NombreBanco { get; set; }
        public string LugarTrabajo { get; set; }
        public Nullable<int> TelefonoTrabajo { get; set; }
        public string FechaIngreso { get; set; }
        public string DireccionTrabajo { get; set; }
        public string FechaFinalizacion { get; set; }
        public string GradoAcademico { get; set; }
        public string Institucion { get; set; }
        public bool Estado { get; set; }
        public string FechaInicio { get; set; }
        public string CarreraTecnica { get; set; }
        public Nullable<int> IdSede { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuloProfesor> ModuloProfesors { get; set; }
    }
}
