//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.CursoEstudiantes = new HashSet<CursoEstudiante>();
        }
    
        public string NombreCurso { get; set; }
        public string CodigoCurso { get; set; }
        public string Duracion { get; set; }
        public string ObjetivoCurso { get; set; }
        public string Metodologia { get; set; }
        public string MaterialDidactico { get; set; }
        public string Certificacion { get; set; }
        public string Inversion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursoEstudiante> CursoEstudiantes { get; set; }
    }
}
