//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estudiante()
        {
            this.CursoEstudiantes = new HashSet<CursoEstudiante>();
            this.ModuloEstudiantes = new HashSet<ModuloEstudiante>();
            this.TecnicoEstudiantes = new HashSet<TecnicoEstudiante>();
        }
    
        public string Nombre { get; set; }
        public int Cedula { get; set; }
        public string FechaIngreso { get; set; }
        public string CarreraTecnica { get; set; }
        public string FechaNacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Genero { get; set; }
        public string TelefonoMovil { get; set; }
        public string TelefonoDomicilio { get; set; }
        public string CorreoElectronico { get; set; }
        public string ReferenciaPersonal { get; set; }
        public string TelefonoReferencia { get; set; }
        public string Provincia { get; set; }
        public string Canton { get; set; }
        public string Distrito { get; set; }
        public string DomicilioExacto { get; set; }
        public string LugarTrabajo { get; set; }
        public string Cargo { get; set; }
        public string TelefonoTrabajo { get; set; }
        public string DireccionTrabajo { get; set; }
        public string GradoAcademico { get; set; }
        public string Institucion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursoEstudiante> CursoEstudiantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuloEstudiante> ModuloEstudiantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TecnicoEstudiante> TecnicoEstudiantes { get; set; }
    }
}
